### ISSUE TITLE
i want to fit image in cell with image aspect fit mode

### ISSUE THREAD

**Issue by cmdr-surender-singh** [techprimate/TPPDF#107]
![simulator screen shot - iphone 8 - 2018-12-28 at 18 31 01](https://user-images.githubusercontent.com/42886349/50516099-ca97d680-0ace-11e9-8d97-ed070830dd72.png)
you can see with screen shot attached my image in particular cell will stretched with 2  row and 5 column

Please resolve my issue i'm stuck on it.

**Comment by philprime** [comment]
Hi there, seems like I missed this issue forever. I am sorry for that!
As a lot has changed since then, I will close this issue, and if necessary, please reopen it

**Comment by dipeshparashar** [comment]
How can we assure the aspect ratio of image ?

**Comment by philprime** [comment]
@dipeshparashar take a look at [Usage](https://github.com/techprimate/TPPDF/blob/master/Documentation/Usage.md#image) in the section about images and the `sizeFit` property

**Comment by dipeshparashar** [comment]
@philprime . I tried all three options, but it did not work.  (I am using version 1.6.0 because the current Cocoapod version throws error due to ./copy keywords used in PDFList files.)

`
        var imageOptions = PDFImageOptions.resize
        if !toResize {
            imageOptions = .none
        }
        
        for image in images {
            let thisPdfImage = PDFImage(image: image,
                                        caption: nil,
                                        size: imageSize,
//                                        sizeFit: .width,  // tried
//                                        sizeFit: .height, // tried
                                        sizeFit: .widthHeight,
                                        quality: 1.0,
                                        options: imageOptions,
                                        cornerRadius: 0)
            existingImages.append(thisPdfImage)
        }

`

Square Image used : https://bit.ly/2AnsMH3 
 
Output : 
![output](https://user-images.githubusercontent.com/8472277/86325640-0086bf80-bc5e-11ea-9233-c36563474248.png)
