### ISSUE TITLE
PDFTable GenerateCell issue 

### ISSUE THREAD

**Issue by jigs777** [techprimate/TPPDF#242]
Please tell me alternative instead of generateCells.
Bcoz table.data method not found new version.
Please give me some code hint how to passed data to PDFTable.
Thank you

**Comment by philprime** [comment]
Hi, first of all please do not create new issues when your previous one was closed. If you have additional information to say, stay in the original issue, because if you actually found an issue, I will thankfully reopen the original one.

Secondly, if you do need help with the framework you should closely read the **documentation**, take a look at the **working examples** and also **provide your code sample** and especially the TPPDF version you are using.
Currently I have absolutely no idea what version you are using, and therefore can't tell you what is wrong.

Please see [Communication](https://github.com/techprimate/TPPDF#communication) on where to ask for what kind of help

**Comment by jigs777** [comment]
@philprime Thanks for the reply.

Please see my old code with old TPPF version.

 **do {
            try table.generateCells(
                data: data ,
                alignments: textAlignment
            )
        } catch PDFError.tableContentInvalid(let value) {
            // In case invalid input is provided, this error will be thrown.
            
            DLog("This type of object is not supported as table content: " + String(describing: (type(of: value))))
        } catch {
            // General error handling in case something goes wrong.
            
            DLog("Error while creating table: " + error.localizedDescription)
        }**


My question is in new version:
How to passed Data & Alignment to PDFTable.
i am trying to do like this:

 let table = PDFTable()
table.alignment method getting but how to data passed to Table.

I hope you understand my issue in new version.

**Comment by philprime** [comment]
What version of TPPDF are you using?

**Comment by jigs777** [comment]
@philprime we are using latest version 2.3.1 and xcode 12.0.1.

**Comment by philprime** [comment]
Well then take a look at the [Table Example](https://github.com/techprimate/TPPDF/blob/master/Shared/Examples/TableExampleFactory.swift) which is available on the `master` branch.
It is a working example you can also try out be opening the Xcode Example Project in the `Examples` folder
