### ISSUE TITLE
NSAttributedText Link is not clickable in generated PDF

### ISSUE THREAD

**Issue by marbetschar** [techprimate/TPPDF#71]
I'm trying to create a PDF containing links which are defined using NSAttributedString. Unfortunately, in the resulting PDF the links are not clickable - only the text is rendered. Here's an example of such an NSAttributedString:

```
if let url = URL(string: "https://google.com") {
    document.addAttributedText(text: NSAttributedString(string: "Mein Link", attributes: [ .link: url ]))
}
```

**Comment by techprimate-phil** [comment]
Please ignore the commit reference, mistake by me.

Attributed strings are rendered using Core Text and links are added using Core Graphics on the PDF context. A simple fix would be adding the url on the frame on the whole attributed string. An advanced approach would be finding the range which contains the URL and only adding the URL on the frame of these characters.
Due to my limited knowledge on Core Text I can only create the simple fix now.

If you want to take a look into this issue, we need to do the following:

- in `PDFAttributedTextObject.draw(_:)` the attributed string is drawn using Core Text
- Enumerate all links in a text:

```swift
        attributedString.enumerateAttribute(.link, in: NSMakeRange(0, attributedString.length), options: []) { (value, range, nil) in
// Find correct frame of range
        }
```

- Add the link in `value` to the frame of `range`. This is the hard part. How can we figure out where the link is drawn? We can set the URL using one of the following methods:

```swift
currentContext.setURL(CFURL, for: CGRect)
```

```swift
UIGraphicsSetPDFContextURLForRect(URL, CGRect)
```

**Comment by diptiganatra** [comment]
@marbetschar Did you get the solution of your problem? Please let me know the solution if you have.

**Comment by marbetschar** [comment]
@diptiganatra and @techprimate-phil unfortunately I no longer work for the project which used to have the clickable URL problem - therefore I can't speak about a definitive solution.

But the approach Phil suggested looks promising. @diptiganatra you might try to create a fork and implement the changes as provided to see how this goes. If its working as intended, a pull request would be awesome!

**Comment by diptiganatra** [comment]
Ok thank you @marbetschar

**Comment by philprime** [comment]
I actually just finished an implementation. It is available on `feature/170-clickable-objects` and I am preparing a merge into `develop` right now
